("Paris"),
("Lyon"),
("Nice"),
("Bordeaux"),
("Strasbourg"),
("Avignon"),
("Versailles,Yvelines"),
("Marseille"),
("Carcassonne"),
("Amiens"),
("Toulouse"),
("Cannes"),
("Angers"),
("Arles")
("Amsterdam"),
("Rotterdam"),
("Maastricht"),
("Warsaw"),
("Vancouver"),
("Niagara Falls"),
("Toronto"),
("Montreal"),
("Victoria,British Columbia"),
("Quebec City"),
("Banff,Alberta"),
("Ottawa"),
("Edmonton"),
("Calgary"),
("Winnipeg"),
("Hamilton,Ontario"),
("Kingston,Ontario"),
("London,Ontario"),
("California"),
("Texas"),
("Florida"),
("Alaska"),
("Hawaii"),
("Utah"),
("New Mexico"),
("Arizona"),
("Nevada"),
("Salt Lake City"),
("San Francisco"),
("New York City"),
("Washington,D.C."),
("Chicago"),
("Philadelphia"),
("New Orleans"),
("Los Angeles"),
("Boston"),
("Miami Beach,Florida"),
("Portland,Oregon"),
("Atlanta"),
("Seattle"),
("Las Vegas"),
("Nashville,Tennessee"),
("Austin,Texas"),
("San Diego"),
("Long Beach,California"),
("Orlando,Florida"),
("Tampa,Florida"),
("Miami")
("Savannah,Georgia"),
("Baltimore"),
("Pittsburgh"),
("Charleston,South Carolina"),
("Houston"),
("Monterey,California"),
("Atlantic City,New Jersey"),
("Detroit"),
("Cleveland"),
("Dallas"),
("Denver"),
("St. Augustine,Florida"),
("Niagara Falls,New York"),
("Sacramento,California"),
("Myrtle Beach,South Carolina"),
("St. Louis"),
("Walt Disney World"),
("Honolulu"),
("Salt Lake City"),
("Cincinnati"),
("Asheville,North Carolina"),
("Minneapolis"),
("Memphis,Tennessee"),
("Santa Fe,New Mexico"),
("Daytona Beach,Florida"),
("New Haven,Connecticut"),
("Rochester,New York"),
("Delray Beach,Florida"),
("Jersey City,New Jersey"),
("Indianapolis"),
("Lisbon"),
("Porto"),
("Sintra"),
("Funchal"),
("Coimbra"),
("Saint Petersburg"),
("Moscow"),
("Kaliningrad"),
("Veliky Novgorod"),
("Kronstadt"),
("Novosibirsk"),
("Pskov"),
("Kuala Lumpur"),
("George Town,Penang"),
("Kota Kinabalu"),
("Kuching"),
("Johor Bahru"),
("Malacca City"),
("Putrajaya"),
("Langkawi"),
("Ipoh"),
("Hong Kong"),
("Shanghai"),
("Beijing"),
("Macau"),
("Lhasa"),
("Nanjing"),
("Shenzhen"),
("Guangzhou"),
("Kowloon"),
("Suzhou"),
("Wuhan"),
("Dalian"),
("Xi27an"),
("Qufu"),
("Hangzhou"),
("Xiamen"),
("Harbin"),
("Qingdao"),
("Chengdu"),
("Shenyang"),
("Kunming"),
("Guilin"),
("Changsha"),
("Ningbo"),
("Tianjin"),
("Zhengzhou"),
("Kashgar"),
("Jinan"),
("Pingyao"),
("Datong"),
("Yangzhou"),
("Lanzhou"),
("Sha Tin"),
("Zhuhai"),
("Haikou"),
("Sanya"),
("Taiyuan"),
("Lijiang"),
("Dengfeng"),
("Yangshuo County"),
("Macau Peninsula"),
("Jiaxing"),
("Quanzhou"),
("Fuzhou"),
("Athens"),
("Thessaloniki"),
("Corfu"),
("Heraklion"),
("Rhodes"),
("Corfu"),
("Delphi"),
("Santorini"),
("Rethymno"),
("Nafplio"),
("Piraeus"),
("Patras"),
("Lindos"),
("Rhodes"),
("Cephalonia"),
("Chania"),
("Ioannina"),
("Mykonos"),
("Mytilene"),
("Chios"),
("Patmos"),
("Epidaurus"),
("Samos"),
("Naxos"),
("Vienna"),
("Salzburg"),
("Innsbruck"),
("Graz"),
("Linz"),
("Klagenfurt"),
("Hallstatt"),
("Bregenz"),
("Osaka"),
("Kyoto"),
("Shinjuku"),
("Nagoya"),
("Tokyo"),
("Chiyoda"),
("Minato"),
("Nara"),
("Hiroshima"),
("Sapporo"),
("Nagasaki"),
("Kamakura"),
("Yokohama"),
("Hakone"),
("Kobe"),
("Kanazawa"),
("Fukuoka"),
("Hakodate"),
("Nagano"),
("Naha"),
("Okayama"),
("Toshima"),
("Kumamoto"),
("Odawara"),
("Himeji"),
("Bonin Islands"),
("Shimonoseki"),
("Sendai"),
("Meguro"),
("London"),
("Edinburgh"),
("Manchester"),
("York"),
("Bath,Somerset"),
("Birmingham"),
("Brighton"),
("Leeds"),
("Newcastle"),
("Glasgow"),
("Liverpool"),
("Oxford"),
("Cardiff"),
("City of London"),
("Blackpool"),
("Belfast"),
("Bristol"),
("Cambridge"),
("Portsmouth"),
("Stratford-upon-Avon"),
("Norwich"),
("Plymouth"),
("Aberdeen"),
("Exeter"),
("Canterbury"),
("Dundee"),
("Sheffield"),
("Chester"),
("Bournemouth"),
("Shrewsbury"),
("Whitby"),
("Leicester"),
("Salisbury"),
("Southampton"),
("Eastbourne"),
("Nottingham"),
("Coventry"),
("Warwick"),
("Bangkok"),
("Ko Tao"),
("Chiang Mai"),
("Pattaya"),
("Ko Samui"),
("Patong"),
("Chiang Rai"),
("Ko Pha-ngan"),
("Ao Nang"),
("Khao Lak"),
("Kanchanaburi"),
("Phuket"),
("Ko Phi Phi"),
("Nakhon Pathom"),
("Hat Yai"),
("Berlin"),
("Hamburg"),
("Munich"),
("Frankfurt"),
("Düsseldorf"),
("Cologne"),
("Dresden"),
("Stuttgart"),
("Koblenz"),
("Bamberg"),
("Potsdam"),
("Füssen"),

("Nuremberg"),
("Trier"),
("Regensburg"),
("Leipzig"),
("Stralsund"),
("Wiesbaden"),
("Essen"),
("Weimar"),
("Lübeck"),
("Heidelberg"),
("Bochum"),
("Dortmund"),
("Aachen"),
("Schwerin"),
("Augsburg"),
("Hanover"),
("Goslar"),
("Rostock"),
("Würzburg"),
("Erfurt"),
("Mexico City"),
("Cozumel"),
("Chichen Itza"),
("Playa del Carmen"),
("Puerto Vallarta"),
("Cabo San Lucas"),
("Palenque"),
("San Miguel de Allende"),

("Guadalajara"),
("Oaxaca City"),
("Cancún"),
("Guanajuato City"),
("Teotihuacan"),
("Querétaro City"),
("Istanbul"),
("Antalya"),
("Alanya"),
("Bursa"),
("Bodrum"),

("Pamukkale"),
("Ankara"),
("Edirne"),
("Adana"),
("Trabzon"),
("Konya"),
("Rome"),
("Venice"),
("Florence"),
("Milan"),
("Siena"),
("Verona"),
("Naples"),
("Catania"),
("Syracuse"),
("Turin"),
("Genoa"),
("Trieste"),
("Pompeii"),
("Pisa"),
("Ferrara"),
("Ravenna"),
("Sicily"),
("Tuscany"),
("Veneto"),
("Sardinia"),
("Capri"),
("Cinque Terre"),
("Andalusia"),
("Catalonia"),
("Canary Islands"),
("Barcelona"),
("Madrid"),
("Seville"),
("Málaga"),
("Granada"),
("Valencia"),
("Toledo,Spain"),
("Bilbao"),
("Puerto de la Cruz"),
("Santa Cruz de Tenerife"),
("Las Palmas"),
("Girona"),
("Salou"),
("Tarragona"),
("Borobudur"),
("Ubud"),
("Jakarta"),
("Prambanan"),
("Bandung"),
("Kuta"),
("Yogyakarta"),
("Nusa Lembongan"),
("Bogor"),
("Sanur,Bali"),
("Nusa Dua"),
("Jimbaran"),
("Medan"),
("Denpasar"),
("Surabaya"),
("Jeju"),
("Seoul"),
("Busan"),
("Gyeongju"),
("Geneva"),
("Zürich"),
("Basel"),
("Zermatt"),
("Bern"),
("Lausanne"),
("Lucerne"),
("Lugano"),
("Dubrovnik"),
("Split"),
("Zagreb"),
("Pula"),
("Zadar"),
("Trogir"),
("Cape Town"),
("Johannesburg"),
("Pretoria"),
("Durban"),
("Stellenbosch"),
("Knysna")
("Budapest"),
("Pécs"),
("Szeged"),
("Eger"),
("Sharm El Sheikh"),
("Hurghada"),
("Luxor"),
("Cairo"),
("Dahab"),
("Alexandria"),
("Aswan"),
("Giza"),
("Marrakesh"),
("Essaouira"),
("Rabat"),
("Casablanca"),
("Dublin"),
("Galway"),
("Limerick"),
("Kilkenny"),
("Killarney"),
("Jaipur"),
("New Delhi"),
("Mamallapuram"),
("Mumbai"),
("Kolkata"),
("Udaipur"),
("Agra"),
("Hampi"),
("Mysore"),
("Amritsar"),
("Fatehpur Sikri"),
("Varanasi"),
("Bangalore"),
("Luxembourg"),
("Vianden"),
("Echternach"),
("Sydney"),
("Melbourne"),
("Perth"),
("Hobart"),
("Brisbane"),
("Canberra"),
("Cairns"),
("Adelaide"),
("Wellington"),
("Auckland"),
("Queenstown"),
("Christchurch"),
("Rotorua"),
("São Paulo"),
("Rio de Janeiro"),
("Salvador,Bahia"),
("Curitiba"),
("Oslo"),
("Bergen"),
("Trondheim"),
("Stavanger"),
("Kristiansand"),
("Helsinki"),
("Tampere"),
("Turku"),
("Ho Chi Minh City"),
("Hanoi"),
("Da Nang"),
("Da Lat"),
("Siem Reap"),
("Phnom Penh"),
("Angkor"),
("Singapore"),
("Fiji"),
("Stockholm"),
("Malmö"),
("Gothenburg"),
("Karlskrona"),
("Visby"),
("Uppsala"),
("Lund"),
("Maldives"),
('North Cape'),
('Aspen,Colorado'),
('Dubai')


// replace 'ö' with 'C3B6'
// replace ' ' with '_',
// replace ',' with '2C ',
// replace '.' with '2e',
// replace 'ü' with 'C3BC',
// replace 'ú' with 'C3BA',
// replace 'é' with 'C3A9',
// replace 'á' with 'C3A1',
// replace 'ã' with 'C3A3'