("Paris"),
("Lyon"),
("Nice"),
("Bordeaux"),
("Strasbourg"),
("Avignon"),
("Versailles,Yvelines"),
("Marseille"),
("Carcassonne"),
("Amiens"),
("Toulouse"),
("Cannes"),
("Angers"),
("Arles")
("Amsterdam"),
("Rotterdam"),
("Maastricht"),
("Warsaw"),
("Vancouver"),
("Niagara Falls,Ontario"),
("Toronto"),
("Montreal"),
("Victoria,British Columbia"),
("Quebec City"),
("Banff,Alberta"),
("Ottawa"),
("Edmonton"),
("Calgary"),
("Winnipeg"),
("Hamilton,Ontario"),
("Kingston,Ontario"),
("London,Ontario"),
("California"),
("Texas"),
("Florida"),
("Alaska"),
("Hawaii"),
("Utah"),
("New Mexico"),
("Arizona"),
("Nevada"),
("Salt Lake City"),
("San Francisco"),
("New York City"),
("Washington,D.C."),
("Chicago"),
("Philadelphia"),
("New Orleans"),
("Los Angeles"),
("Boston"),
("Miami Beach,Florida"),
("Portland,Oregon"),
("Atlanta"),
("Seattle"),
("Las Vegas"),
("Nashville,Tennessee"),
("Austin,Texas"),
("San Diego"),
("Long Beach,California"),
("Orlando,Florida"),
("Tampa,Florida"),
("Miami")
("Savannah,Georgia"),
("Baltimore"),
("Pittsburgh"),
("Charleston,South Carolina"),
("Houston"),
("Monterey,California"),
("Atlantic City,New Jersey"),
("Detroit"),
("Cleveland"),
("Dallas"),
("Denver"),
("St. Augustine,Florida"),
("Niagara Falls,New York"),
("Sacramento,California"),
("Myrtle Beach,South Carolina"),
("St. Louis"),
("Walt Disney World"),
("Honolulu"),
("Salt Lake City"),
("Cincinnati"),
("Asheville,North Carolina"),
("Minneapolis"),
("Memphis,Tennessee"),
("Santa Fe,New Mexico"),
("Daytona Beach,Florida"),
("New Haven,Connecticut"),
("Rochester,New York"),
("Delray Beach,Florida"),
("Jersey City,New Jersey"),
("Indianapolis"),
("Lisbon"),
("Porto"),
("Sintra"),
("Funchal"),
("Coimbra"),
("Saint Petersburg"),
("Moscow"),
("Kaliningrad"),
("Veliky Novgorod"),
("Kronstadt"),
("Novosibirsk"),
("Pskov"),
("Kuala Lumpur"),
("George Town,Penang"),
("Kota Kinabalu"),
("Kuching"),
("Johor Bahru"),
("Malacca City"),
("Putrajaya"),
("Langkawi"),
("Ipoh"),
("wv Hong Kong"),
("wv Shanghai"),
("wv Beijing"),
("wv Macau"),
("Lhasa"),
("Nanjing"),
("Shenzhen"),
("Guangzhou"),
("Kowloon"),
("Suzhou"),
("Wuhan"),
("Dalian"),
("Xi27an"),
("Qufu"),
("Hangzhou"),
("Xiamen"),
("Harbin"),
("Qingdao"),
("Chengdu"),
("Shenyang"),
("Kunming"),
("Guilin"),
("Changsha"),
("Ningbo"),
("wv Tianjin"),
("Zhengzhou"),
("Kashgar"),
("Jinan"),
("Pingyao"),
("Datong"),
("Longmen Grottoes"),
("Sai Ying Pun"),
("Yangzhou"),
("Lanzhou"),
("Sha Tin"),
("Zhuhai"),
("Haikou"),
("Sanya"),
("Taiyuan"),
("Lijiang"),
("Dengfeng"),
("Yangshuo County"),
("Macau Peninsula"),
("wv Chongqing"),
("Jiaxing"),
("Quanzhou"),
("Fuzhou"),
("Athens"),
("Thessaloniki"),
("Corfu"),
("Heraklion"),
("Rhodes 28city29"),
("Corfu 28city29"),
("Delphi"),
("Santorini"),
("Rethymno"),
("Nafplio"),
("Piraeus"),
("Olympia,Greece"),
("Patras"),
("Lindos"),
("Rhodes"),
("Cephalonia"),
("Chania"),
("Ioannina"),
("Mykonos"),
("Mytilene"),
("Oia,Greece"),
("Chios"),
("Patmos"),
("Epidaurus"),
("Samos"),
("Naxos"),
("wv Vienna"),
("Salzburg"),
("Innsbruck"),
("Graz"),
("Linz"),
("Klagenfurt"),
("Hallstatt"),
("Bregenz"),
("Osaka"),
("Kyoto"),
("Shinjuku"),
("Nagoya"),
("Tokyo"),
("Chiyoda,Tokyo"),
("Minato,Tokyo"),
("Nara,Nara"),
("Hiroshima"),
("TaitC58D"),
("Sapporo"),
("Nagasaki"),
("Matsumoto,Nagano"),
("Sumida,Tokyo"),
("Kamakura"),
("Takayama,Gifu"),
("Yokohama"),
("Hakone"),
("Kobe"),
("Kanazawa"),
("Fukuoka"),
("Hakodate"),
("Nagano 28city29"),
("Naha"),
("Okayama"),
("Toshima"),
("Kumamoto"),
("Narita,Chiba"),
("Odawara"),
("Tsukuba,Ibaraki"),
("Himeji"),
("Bonin Islands"),
("Shirakawa,Gifu 28village29"),
("Mito,Ibaraki"),
("Shimonoseki"),
("Fujinomiya,Shizuoka"),
("Sendai"),
("Takamatsu,Kagawa"),
("Meguro"),
("London"),
("Edinburgh"),
("Manchester"),
("York"),
("Bath,Somerset"),
("Birmingham"),
("Brighton"),
("Leeds"),
("Newcastle upon Tyne"),
("Glasgow"),
("Liverpool"),
("Oxford"),
("Cardiff"),
("City of London"),
("Blackpool"),
("Belfast"),
("Bristol"),
("Windsor,Berkshire"),
("Cambridge"),
("Portsmouth"),
("Stratford-upon-Avon"),
("Norwich"),
("Plymouth"),
("Aberdeen"),
("Lincoln,England"),
("Exeter"),
("Canterbury"),
("Kingston upon Hull"),
("Dundee"),
("Sheffield"),
("Chester"),
("Scarborough,North Yorkshire"),
("Bournemouth"),
("Shrewsbury"),
("St Andrews"),
("Reading,Berkshire"),
("Whitby"),
("Leicester"),
("Keswick,Cumbria"),
("Stirling"),
("Salisbury"),
("Inverness"),
("Swansea"),
("Torquay"),
("Southampton"),
("Eastbourne"),
("Nottingham"),
("Llandudno"),
("Coventry"),
("Warwick"),
("Bangkok"),
("Ko Tao"),
("Chiang Mai"),
("Pattaya"),
("Ko Samui"),
("Patong"),


("Chiang Rai"),
("Ko Pha-ngan"),
("Ko Lanta District"),
("Ao Nang"),
("Khao Lak"),
("Kanchanaburi"),
("Phuket 28city29"),
("Ko Chang District"),
("Ko Phi Phi Don"),
("Nakhon Pathom"),
("Hat Yai"),
("wv Berlin"),
("wv Hamburg"),
("Munich"),
("Frankfurt"),
("Düsseldorf"),
("Cologne"),
("Dresden"),
("Stuttgart"),
("Koblenz"),
("Bamberg"),
("Potsdam"),
("Füssen"),

("Nuremberg"),
("Trier"),
("Regensburg"),
("Leipzig"),
("Stralsund"),
("Wiesbaden"),
("Essen"),
("Weimar"),
("Lübeck"),
("Heidelberg"),
("wv Bremen"),
("Bochum"),
("Dortmund"),
("Aachen"),
("Schwerin"),
("Augsburg"),
("Hanover"),
("Goslar"),
("Rostock"),
("Würzburg"),
("Erfurt"),
("Mexico City"),
("Cozumel"),
("Chichen Itza"),
("Playa del Carmen"),
("Puerto Vallarta"),
("Cabo San Lucas"),
("Palenque"),
("San Miguel de Allende"),

("Guadalajara"),
("Oaxaca City"),
("Cancún"),
("Guanajuato City"),
("Teotihuacan"),
("Querétaro City"),
("Istanbul"),
("Antalya"),
("Alanya"),
("Bursa"),
("Bodrum"),

("Pamukkale"),
("Ankara"),
("Edirne"),
("Adana"),
("Trabzon"),
("Konya"),
("Rome"),
("Venice"),
("Florence"),
("Milan"),
("Siena"),
("Verona"),
("Naples"),
("Catania"),
("Syracuse,Sicily"),
("Turin"),
("Genoa"),
("Trieste"),
("Pompeii"),
("Pisa"),
("Ferrara"),
("Ravenna"),
("wv Sicily"),
("wv Tuscany"),
("wv Abruzzo"),
("wv Veneto"),
("wv Sardinia"),
("Capri"),
("Cinque Terre National ParK"),
("wv Andalusia"),
("wv Catalonia"),
("wv Canary Islands"),

("Barcelona"),
("Madrid"),
("Seville"),
("Málaga"),
("Granada"),
("Valencia"),
("Toledo,Spain"),
("Bilbao"),
("Puerto de la Cruz"),
("Santa Cruz de Tenerife"),
("Las Palmas"),
("Girona"),
("Salou"),
("Tarragona"),
("wv Bal"),
("Borobudur"),
("Ubud"),
("Jakarta"),
("Prambanan"),
("Bandung"),
("Kuta"),
("Yogyakarta"),
("Nusa Lembongan"),
("Bogor"),
("Sanur,Bali"),
("Nusa Dua"),
("Jimbaran"),
("Medan"),
("Denpasar"),
("Surabaya"),
("wv Jeju"),
("Seoul"),
("Busan"),
("Gyeongju"),
("Geneva"),
("Zürich"),
("Basel"),
("Zermatt"),
("Bern"),
("Lausanne"),
("Lucerne"),
("Lugano"),
("Dubrovnik"),
("Split,Croatia"),
("Zagreb"),
("Pula"),
("Zadar"),
("Trogir"),
("Cape Town"),
("Johannesburg"),
("Pretoria"),
("Durban"),
("Stellenbosch"),
("Knysna")
("Budapest"),
("Pécs"),
("Szeged"),
("Eger"),
("Sharm El Sheikh"),
("Hurghada"),
("Luxor"),
("Cairo"),
("Dahab"),
("Alexandria"),
("Aswan"),
("Giza"),
("Marrakesh"),
("Essaouira"),
("Rabat"),
("Casablanca"),
("Dublin"),
("Galway"),
("Limerick"),
("Kilkenny"),
("Killarney"),
("Jaipur"),
("New Delhi"),
("Mamallapuram"),
("Mumbai"),
("Kolkata"),
("Udaipur"),
("Agra"),
("Hampi"),
("Mysore"),
("Amritsar"),
("Fatehpur Sikri"),
("Varanasi"),
("Bangalore"),
("Luxembourg City"),
("Vianden"),
("Echternach"),
("Sydney"),
("Melbourne"),
("Perth"),
("Hobart"),
("Brisbane"),
("Canberra"),
("Cairns"),
("Adelaide"),
("Wellington"),
("Auckland"),
("Queenstown,New Zealand"),
("Christchurch"),
("Rotorua"),
("São Paulo"),
("Rio de Janeiro"),
("Salvador,Bahia"),
("BrasC3ADlia"),
("Curitiba"),
("Oslo"),
("Bergen"),
("Trondheim"),
("Stavanger"),
("Kristiansand"),
("Helsinki"),
("Tampere"),
("Turku"),
("Ho Chi Minh City"),
("Hanoi"),
("Da Nang"),
("Da Lat"),
("Siem Reap"),
("Phnom Penh"),
("Angkor"),
("Singapore"),
("Fiji"),
("Stockholm"),
("Malmö"),
("Gothenburg"),
("Karlskrona"),
("Visby"),
("Uppsala"),
("Lund"),
("Maldives"),
('North Cape'),
('Aspen,Colorado'),
('Dubai')


// replace 'ö' with 'C3B6'
// replace ' ' with '_',
// replace ',' with '2C ',
// replace '.' with '2e',
// replace 'ü' with 'C3BC',
// replace 'ú' with 'C3BA',
// replace 'é' with 'C3A9',
// replace 'á' with 'C3A1',
// replace 'ã' with 'C3A3'